### ISSUE TITLE
dpkg: error: cannot access archive 'vc4c_v0.4-3-20190206_armhf.deb': No such file or directory

### ISSUE THREAD

**Issue by spinoza1791** [thortex/rpi3-vc4cl#1]
pi@raspberrypi:~/rpi3-vc4cl $ ./022_install_vc4c.sh
+ R=v0.4-3
+ D=20190206
+ U=https://github.com/thortex/rpi3-vc4cl/releases/download/
+ F=vc4c_v0.4-3-20190206_armhf.deb
+ wget -c https://github.com/thortex/rpi3-vc4cl/releases/download/v0.4-3/vc4c_v0.4-3-20190206_armhf.deb
--2019-02-10 21:05:52--  https://github.com/thortex/rpi3-vc4cl/releases/download/v0.4-3/vc4c_v0.4-3-20190206_armhf.deb
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-02-10 21:05:52 ERROR 404: Not Found.

+ sudo dpkg -i vc4c_v0.4-3-20190206_armhf.deb
dpkg: error: cannot access archive 'vc4c_v0.4-3-20190206_armhf.deb': No such file or directory

**Comment by thortex** [comment]
635c0c4e25cd2d9c3402215a03a0c3e2bb6e5e5f

**Comment by spinoza1791** [comment]
that fixed it.  Thx!
